[project]
name = "app"
version = "0.1.0"
description = "LLM Engineers Handbook"
requires-python = ">=3.12"

homepage = "https://github.com/stanimirdim92/llms"
keywords = []
readme = "README.md"
packages = [
    { include = "app" },
]
license = "Apache-2.0"
dependencies = [
    #    "python>=3.12,<4.0",
    "python-dotenv>=1.0",
    "langchain>=1",
    "langchain-core>=1",
    "langchain-community>=0.4",
    "langchain-openai>=1",
    "langchain-text-splitters>=1",
    "langsmith>=0.4",
    "langchain-google-community>=3.0",
    "langgraph>=1",
    #    poppler-utils  = "^0"
    #    gunicorn = "^23"
    #    aiomysql = "^0.2"
    #    #pymupdf = "^1.26"
    #    pillow = "^11"
    #    beautifulsoup4 = "^4.14"
    #    #qreader = "^3.14" # installs cuda, torch, ultralitics, etc., way to big
    #    pyzbar= "^0"
    #    tf-playwright-stealth = "^1.2"
    #    playwright = "^1.55"
    #    cachetools = "^6"
    #    fastapi = "^0.118"
    #    uvicorn = "^0.37"
    #    sse-starlette = "^3"
    #    sqlmodel = "^0.0.27"
    #    googlemaps = "^4.10"
    #    #celery = {extras = ["redis"], version = "^5.5"}
    #    lxml = "^6"
    #
    #    cryptography = "^46"
    #    "unstructured[pdf]>=0.18.15",
    "ruff>=0.14.2",
    "orjson>=3.11.4",
    "uvloop>=0.22.1",
    "pydantic>=2.12.3",
    "redis[hiredis]>=7.0.1",
    "gunicorn>=23.0.0",
    "uvicorn>=0.38.0",
    "fastapi[standard]>=0.120.1",
    "ty>=0.0.31",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""
