FROM nginx:latest

RUN apt-get update &&  \
    apt-get upgrade -y && \
    apt-get install -y \
    logrotate

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/default_dev.conf /etc/nginx/conf.d/default.conf

# Create 'messages' file used from 'logrotate'
RUN touch /var/log/messages

# Copy 'logrotate' config file
COPY logrotate/nginx /etc/logrotate.d/

EXPOSE 80 443
