"""ingestion_version: publish by flipping an active generation

Revision ID: 307f47df6135
Revises: 2adf560892da
Create Date: 2026-08-06 07:06:27.750976
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

# The submodule, explicitly: autogenerated columns reference
# `sqlmodel.sql.sqltypes.AutoString`, and a bare `import sqlmodel` leaves that a
# possibly-unimported submodule to the type checker.
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op

revision: str = "307f47df6135"
down_revision: str | None = "2adf560892da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # **Refuses to run against a non-empty table, and that is the point of this migration.**
    #
    # Every point already in Qdrant was written without an `ingestion_version` payload key, and a
    # `MatchAny` on a missing key matches nothing (probe-verified against qdrant_client). Retrieval
    # admits only active versions, so the instant this column exists every previously-ingested
    # document goes dark: its row still says `ingested`, `list_active_versions` skips it for having
    # no version, and an unscoped /ask answers from the tenant's *other* documents with nothing
    # raised. That is the exact failure versioned ingestion exists to close, delivered to the whole
    # corpus at once instead of on a rare crash -- rule 8's "shipping a column that silently
    # disables every existing record".
    #
    # There is no honest backfill: a version invented here would have to match points that carry no
    # version at all. So the deploy is refused and the operator re-ingests, which is loud and
    # recoverable. The alternative -- a nullable version meaning "don't filter" -- readmits every
    # superseded point ever written, which is the inverse rule-8 error.
    rows = op.get_bind().execute(sa.text("SELECT count(*) FROM documentrecord")).scalar()
    if rows:
        msg = (
            f"documentrecord has {rows} row(s). Points written before this revision carry no "
            "ingestion_version and would become permanently unsearchable while still reporting "
            "'ingested'. Drop the Qdrant collection and this table, then re-upload."
        )
        raise RuntimeError(msg)

    op.add_column("documentrecord", sa.Column("ingestion_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(
        op.f("ix_documentrecord_ingestion_version"), "documentrecord", ["ingestion_version"], unique=False
    )


def downgrade() -> None:
    # Dropping the column is the easy half and the code is the hard half: on this schema
    # `QdrantStore.upsert` deletes nothing, so a downgraded database has no way to express which
    # generation is live and every generation becomes readable at once. Downgrade only alongside
    # reverting the code, and drop the Qdrant collection when you do.
    op.drop_index(op.f("ix_documentrecord_ingestion_version"), table_name="documentrecord")
    op.drop_column("documentrecord", "ingestion_version")
