"""initial schema: tenant, apikey, documentrecord

Revision ID: 2adf560892da
Revises:
Create Date: 2026-08-06 05:13:57.683701
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

# The submodule, explicitly: autogenerated columns reference
# `sqlmodel.sql.sqltypes.AutoString`, and a bare `import sqlmodel` leaves that a
# possibly-unimported submodule to the type checker.
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op

revision: str = "2adf560892da"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentrecord",
        sa.Column("doc_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_extension", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(op.f("ix_documentrecord_status"), "documentrecord", ["status"], unique=False)
    op.create_index(op.f("ix_documentrecord_tenant_id"), "documentrecord", ["tenant_id"], unique=False)
    op.create_table(
        "tenant",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apikey",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apikey_expires_at"), "apikey", ["expires_at"], unique=False)
    op.create_index(op.f("ix_apikey_key_hash"), "apikey", ["key_hash"], unique=True)
    op.create_index(op.f("ix_apikey_tenant_id"), "apikey", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apikey_tenant_id"), table_name="apikey")
    op.drop_index(op.f("ix_apikey_key_hash"), table_name="apikey")
    op.drop_index(op.f("ix_apikey_expires_at"), table_name="apikey")
    op.drop_table("apikey")
    op.drop_table("tenant")
    op.drop_index(op.f("ix_documentrecord_tenant_id"), table_name="documentrecord")
    op.drop_index(op.f("ix_documentrecord_status"), table_name="documentrecord")
    op.drop_table("documentrecord")
    # ### end Alembic commands ###
