# Local dev: plain HTTP, no domain, no cert-provisioning scaffolding (that's in
# default.conf instead, since it's actually relevant there once a real domain exists).
server {
    listen 80 default_server reuseport backlog=1024;
    server_name localhost;

    access_log /var/log/nginx/portfolio.access.log main buffer=512k flush=1m;
    error_log /var/log/nginx/portfolio.error.log warn;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
        proxy_ignore_headers    X-Accel-Expires Expires Cache-Control Set-Cookie;
        proxy_redirect off;
        proxy_buffering off;
        proxy_buffer_size 24k;
        proxy_busy_buffers_size 24k;
        proxy_buffers 64 4k;
        proxy_connect_timeout  315s;
        proxy_send_timeout  315s;
        proxy_read_timeout  315s;
        proxy_pass http://portfolio_api;
        proxy_next_upstream error timeout http_500;

        aio threads;
    }

    location = /favicon.ico {
        log_not_found off;
    }

    location = /robots.txt {
        log_not_found off;
    }

    location ~* /\.(?!well-known\/) {
      deny all;
    }

    location ~* (?:#.*#|\.(?:bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op])|~)$ {
      deny all;
    }
}
