"""Alembic environment, driven both from the CLI and from `app/db.py::init_db`.

Two things here are load-bearing and easy to undo:

1. **`include_object` excludes `procrastinate_*`.** Procrastinate owns its own schema and applies it
   itself (`app/db.py::_apply_procrastinate_schema`); its tables are not in `SQLModel.metadata`. To
   `--autogenerate` that difference reads as "these tables should not exist", so without this filter
   the first generated migration cheerfully drops the entire job queue.
2. **The URL comes from `app/config.py`, never from `alembic.ini`.** It embeds the Postgres password
   and is a `SecretStr`; a URL in the ini file is both a second source of truth and something a real
   credential can be committed into.
"""

from __future__ import annotations

import asyncio

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlmodel import SQLModel

# Importing every model module is what populates `SQLModel.metadata`. A model whose module is not
# imported here is invisible to autogenerate, and the migration silently omits its table -- the same
# failure `app/db.py::init_db` documents for `create_all`.
from app.auth import models as _auth_models  # noqa: F401
from app.config import get_settings
from app.registry import models as _registry_models  # noqa: F401

config = context.config
# No `fileConfig(config.config_file_name)`. Alembic's template calls it, which requires
# `[formatters]`/`[handlers]`/`[loggers]` sections in `alembic.ini` -- and this project configures
# logging once, through structlog (`app/logs.py`). A second logging config would either fight it or
# silently replace it during migrations, so the sections are absent and this call is gone with them.

target_metadata = SQLModel.metadata

_PROCRASTINATE_PREFIX = "procrastinate_"


def include_object(object_, name, type_, reflected, compare_to) -> bool:  # noqa: ANN001, ARG001
    """Keep procrastinate's own objects out of every comparison. See this module's docstring."""
    if type_ == "table" and name is not None and name.startswith(_PROCRASTINATE_PREFIX):
        return False
    return not (type_ == "index" and name is not None and name.startswith(_PROCRASTINATE_PREFIX))


def _configure(connection) -> None:  # noqa: ANN001
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        # Detect column type changes as well as added/removed columns. Off by default, and its
        # absence is why an autogenerated migration can look complete while missing a type change.
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_offline() -> None:
    context.configure(
        url=get_settings().database_url.get_secret_value(),
        target_metadata=target_metadata,
        include_object=include_object,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    # `init_db` passes its own connection so the migration runs inside the transaction already
    # holding the advisory lock. Without that the lock would not cover the migration at all, and
    # concurrent booting processes would race the DDL -- the failure the lock exists to prevent.
    connection = config.attributes.get("connection")
    if connection is not None:
        _configure(connection)
        return

    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = get_settings().database_url.get_secret_value()
    engine = async_engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    async def _run() -> None:
        async with engine.connect() as conn:
            await conn.run_sync(_configure)
            await conn.commit()
        await engine.dispose()

    asyncio.run(_run())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
